spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?serverTimezone=GMT
    username: root
    password: a5850246
mybatis:
  config-location: classpath:mybatis-config.xml
server:
  port: 80
#log级别
logging :
    level :
      root : wran
#springframework.web日志以DEBUG级别输出
      org:
        springframework:
          web: debug
#日志保存的本地路径
    file: F:/upload/wangdaonews.log
#日志格式
